### ISSUE TITLE
Per namespace security

### ISSUE THREAD

**Issue by alex-zywicki** [dedoussis/asynction#129]
As a continuation of #110 It would be very helpful to be able to customize security schemes on a per namespace level.
Currently asyncapi does not support this, so it would need to be in the form of a `x-security` specification.

One of the main questions I see is how per namespace security would interact with global security. Would it override global level security? or would both have to pass?

**Comment by dedoussis** [comment]
Thanks for the contribution @alex-zywicki! This functionality has been released as part of version `0.6.0`. Closing the issue.
