### ISSUE TITLE
docs: contribution section

### ISSUE THREAD

**Issue by pedrohbtp** [dedoussis/asynction#19]
Great work with this library!
I am a fan of specification first and have been using connexion for a while.
It would be great if you specified some milestones and contribution guidelines so people like me can help you.
Great work!

**Comment by dedoussis** [comment]
Hey @pedrohbtp ! Good point. Will put some docs together in the coming days.

**Comment by pedrohbtp** [comment]
Thanks for the work!
Do you know other tools for a documentation first approach for AsyncApi from other languages as an inspiration?
I have not found any while searching.

**Comment by dedoussis** [comment]
@pedrohbtp I've created a PR that introduces contribution guidelines as you suggested. You're more than welcome to review it.

https://github.com/dedoussis/asynction/pull/20

**Comment by dedoussis** [comment]
> Do you know other tools for a documentation first approach for AsyncApi from other languages as an inspiration?
I have not found any while searching.

AFAIK, there is no other similar tool for AsyncAPI, in any other language. Asynction is the first of its kind 😄 .

However the OpenAPI counterparts (ie [Connexion](https://github.com/zalando/connexion) and [openapi-backend](https://github.com/anttiviljami/openapi-backend)) could offer a great source of inspiration.
